name: Tracky AI CI

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Test code & styles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build test image
        run: | 
          touch .env
          docker compose build trackyai-test
      - name: Run ruff
        run: |
          docker compose run --rm trackyai-test /bin/bash -c "ruff check --config .ruff.toml"
      - name: Run mypy
        run: |
          docker compose run --rm trackyai-test /bin/bash -c "mypy trackyai --install-types --non-interactive --show-traceback --raise-exceptions --config-file mypy.ini"
      - name: Run tests
        run: docker compose run --rm trackyai-test
